image: node:8.12.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@7.0.2
  - npm install
  - ng lint
  - ng build --prod
  artifacts:
    paths:
    - public
  only:
  - develop
  - pages